# 回调模式
回调是反应器模式的具体实现，它对Node.js特有的代码风格影响很大。在将操作的结果传输出去的时候触发，这正是我们处理异步操作的时候所需要的，几乎将同步操作典型的`return`完全替换掉了。因为函数在JavaScript中是一等公民，可以赋值给变量、作为参数传递、从另外一个函数触发、保存到数据结构中，所以JavaScript可以将回调的作用发挥到极致。同时，闭包也是实现回调的理想结构。利用闭包，我们可以确定地使用函数创建时的环境，不管函数在哪调用，函数的上下文都和创建时的上下文相关。
> 如果你想复习一下闭包的知识，你可以参考Mozilla开发者网络中的文章：[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures)。

在这一节，我们将讨论由回调构成的编码风格，而不是`return`指令。

## 连续传递风格
在JavaScript中，回调函数被作为一个参数传递到另外一个函数，在函数执行完成时，回调函数被触发的同时，传入执行结果。在函数式编程中，这种传递结果的方式叫做`连续传递风格`，简称CPS。这是一个通用概念，并不总是和异步操作相关。简单来说，就是结果被传递给另外一个函数（回调函数），而不是直接返回给调用者。
### 同步的连续传递风格
为了搞清楚这个概念，我们先看一下这个简单的同步函数：

```
function add(a,b) {
	return a + b;
}
```
这并没有什么特别的；结果利用`return`指令返回给调用者；这也成为`直接风格`，这是同步编程中最常见的结果返回方式。同样地，利用CPS风格实现前面这个函数的方法如下：

```
function add(a, b, callback) {
	callback(a +  b);
}
```
`add()`是一个同步的CPS函数，这意味着只有当回调函数执行完成之后才能返回值。见下面的代码：

```
console.log('执行前');
add(1,2,function(result){
	console.log('结果是：'+result);
});
console.log('执行后');
```
因为`add()`是同步的，所以很明显上述代码执行将打印如下内容：

```
执行前
结果是：3
执行后
```
### 异步的连续传递风格
下面考虑当`add()`是异步函数的情况：

```
function addAsync(a, b, callback) {
  setTimeout(function() {
    callback(a + b);
  }, 100);
}
```
在上面的代码中，我们使用`setTimeout()`函数来模拟异步调用回调函数。试着使用这个函数，来看看和之前有没有什么区别

```
console.log('执行前');
add(1,2,function(result){
	console.log('结果是：'+result);
});
console.log('执行后');
```
执行结果如下：

```
执行前
执行后
结果是：3
```
既然`setTimeout()`触发了一个异步操作，他不会等着回调执行完。但它会立刻将控制权返还给`addAsync()`，然后返还给调用者。这个特性在Node.js中非常关键，它允许栈展开，当异步请求一发送，就会把控制权返还给事件循环，这样才能让队列中新的事件被处理到。
下图展示了它是怎么工作的：
![](../images/addSync.png)
当异步操作完成后，重新从提供给（引起栈展开的）异步函数的回调开始执行。从事件循环开始执行，它将会拥有一个全新的栈。JavaScript的这一点非常方便，基于闭包，这样即便是回调在不同的时间点执行，也可以保存函数创建时的上下文。

> 注：同步函数是阻塞的，直至完成操作。异步函数立即返回，结果传入处理器（这种情况下是回调函数），在下一次事件循环时执行。

### 非连续传递风格的回调
有些情况下，回调风格的参数可能会让你误以为这个函数是异步的或者是采用了连续传递风格的编码；其实这样想不一定对，举个例子，`Array`对象的`map()`函数：

```
var result=[1,5,7].map(function(element){
	return element-1;
});
```
显然，这个回调只是用来遍历数组的元素，并不传递运行的结果。事实上，结果采用同步风格返回。回调函数的作用会在文档中明确说明。

## 同步还是异步
根据指令执行的顺序不同，分为同步和异步。这对程序的正确性和效率有或多或少的影响。下面是对两种写法的分析，还有他们各自的缺点。一般说来，应该避免写出前后不一致或者让人疑惑的代码，这样做可能会引入一系列难以发现和重现的问题。我们将采用前后不一致的代码来支撑我们的分析。
### 不可预测结果的函数
一个函数有时候同步有时候异步是一件非常危险的事情。举个例子：

```
var fs = require('fs');
var cache = {};
function inconsistentRead(filename, callback) {
  if(cache[filename]) {
    //同步触发
    callback(cache[filename]);  
  } else {
    //异步函数
    fs.readFile(filename, 'utf8', function(err, data) {
      cache[filename] = data;
      callback(data);
    });
  }
}
```
前一个函数使用`cache`变量来存储不同不同文件的读取结果。请记住这只是一个例子，它没有错误管理，缓存管理逻辑也不是最优的。除此之外，上面的程序在没有命中缓存的时候是异步的（直到`fs.readFile()`返回结果），但是接下来的请求会同步地访问到缓存，直接触发回调。
### 释放恶魔
现在，我们来看一下刚才定义的不可预期的函数怎样使一个程序崩溃的。看下面的代码：

```
function createFileReader(filename) {
  var listeners = [];
  inconsistentRead(filename, function(value) {
    listeners.forEach(function(listener) {
      listener(value);
    });
  });

  return {
    onDataReady: function(listener) {
      listeners.push(listener);
    }
  };
}
```
当前面的函数被触发，会创建一个新的对象，作为一个通知器，可以为文件读取操作设置一些监听器。当读取操作完成时，所有的的监听器都会被触发。前面的函数利用`inconsistentRead()`函数来实现功能。我们来试着使用一下`createFileReader()`函数。

```
var reader1 = createFileReader('data.txt');  
reader1.onDataReady(function(data) {
  console.log('First call data: ' + data);
  //过会再从同一个文件读
  var reader2 = createFileReader('data.txt');
  reader2.onDataReady(function(data) {
    console.log('Second call data: ' + data);
  });
});    
```
前面的代码将打印如下输出：

```
First call data : some data
```
第二个操作的回调没有被触发，来看看是为什么：

* 在创建`reader1`的过程中，`inconsistentRead()`函数表现为异步操作，因为没有缓存的过过。因此，我们可以利用这段时间来注册监听器，将会在读取操作完成后的下一轮事件循环触发。
* 然后，`reader2`在文件缓存已经存在之后的事件循环中被创建。这样，内部对`inconsistentRead()`的调用是同步的。所以，回调会被立即触发，这同样意味着`reader2`的所有监听器将会同步触发。但是我们是在`reader2`创建完成后注册的监听器，所以他们不会被触发。

> 译者注：因为每次listeners都是清空的，如果不是清空的，可能会陷入死循环。

`inconsistentRead()`的回调行为结果真是不可预期的，因为它和很多因素关联，比如触发的频次、以参数的形式传入的文件名、加载文件的时间等。
我们刚刚创建的bug在实际应用中可能会很难识别、重现。假设我们在一个web服务器中使用一个类似的函数，可能有大量的并发请求；假设看到了有些请求挂起了，也找不到任何明显的原因，也没有错误日志。这毫无疑问会被归为`令人讨厌的缺陷`。
Isaac Z. Schlueter，`npm`的创建者和Node.js项目的早起领导者，在他的博客中将这类不可预测函数的使用比作`释放魔鬼`。如果你不知道什么是Zalgo，你可以自己去搞清楚。
> 注：你可以在[这里](http://blog.izs.me/post/59142742143/designing-apis-for-asynchrony)找到Isaac的原始文章。
### 使用同步API
从上一节的例子中，我们学到一个API在定义的时候就要确定清楚是同步的还是异步的。
修复`inconsistentRead()`函数的一个可用的手段是把它编程纯同步的。这个方法是可行的是因为Node.js为基础的I/O操作提供了一系列的同步的API。比如，我们可以用`fs.readFileSync()`函数来替换相应的同步函数。新的代码如下：

```
var fs=require('fs');
var cache= {};
function consistentReadSync(filename){
	if(cache[filename]){
		return cache[filename];
	}else{
		cache[filename]=fs.readFileSync(filename,'utf8');
		return cache[filename];
	}
}
```
可以看到，整个函数都转化成了直接的风格。如果函数是同步的，没必要采用CPS风格。最佳实践其实是用直接的方式实现一个同步的函数。这将从根本上减少让人疑惑的部分，从性能角度考虑也更好。
> 注：模式：纯同步方法宜采用直接写法。

需要牢记的是，把一个API从CPS转换为直接方式，从异步转为同步，或者反过来，都需要修改它的写法。在我们的例子中，需要完全修改`createFileReader()`的接口写法，已适应同步的运行模式。
同样，使用同步方法而不是异步方法的过程中，需要注意以下内容：

* 并不是所有需要同步功能的时候都会有同步的API。
* 同步API会阻塞事件循环，导致并发请求暂停。这将会使Node.js丧失并发能力，使整个应用速度减慢。在此书的后面，我们可以看到这到底意味着什么。

在`consistentReadSync()`函数中，阻塞事件循环的风险因为每个文件名只会触发一次同步I/O可以有一定程度的缓解，缓存的内容会被后面的请求复用。如果我们只有少量的静态文件，使用`consistentReadSync()`并不会对事件循环有太大的影响。如果我们需要读取很多文件时，情况就大不一样了。在很多情形下，非常不推荐使用同步I/O；但在某些情况下，这可能是最简单最有效的解决方案。这需要评估特定的引用场景，选择合适的方案。

> 提示： 当不影响并发请求时使用阻塞API。

### 延后执行
另外一个修复`inconsistentRead()`函数的备选方案是把它变成纯异步的。实现的手段是安排本应立刻执行的同步回调的触发在一段时间之后再执行。在Node.js中，可以使用`process.nextTick()`，将函数的执行推迟到下一轮事件循环。这非常容易实现；它把一个回调函数作为参数，并把它事件队列的顶端，在所有等待的I/O事件的最前面，并立即返回。当事件循环再次运行的时候，回调函数可以立即执行。
让我们用这种技术来修复`inconsistentRead()`函数：

```
var fs = require('fs');
var cache = {};
function consistentReadAsync(filename, callback) {
  if(cache[filename]) {
    process.nextTick(function() {
      callback(cache[filename]);
    });
  } else {
    //asynchronous function
    fs.readFile(filename, 'utf8', function(err, data) {
      cache[filename] = data;
      callback(data);
    });
  }
}
```
这就确保了我们的函数在任何情况下都能异步触发。
另外一个用于推迟执行的API是`setImmediate()`。虽然从名字上看它会很快执行，但实际上它会比`process.nextTick()`更慢一些。虽然他们的作用非常相似，但是他们的机制有很大差别。使用`process.nextTick()`推迟的回调会先于其它事件触发，而使用	`setImmediate()`，回调后比队列中已有的I/O事件都晚。因为`process.nextTick()`先于其它编排好的I/O事件执行，在某些情况下，这了能导致饿死，比如在递归调用时。使用`setImmediate()`就不会出现这种情况。我们后面分析使用延迟触发来处理CPU相关操作的任务时，就可以进一步了解两种不同的API的差别。

> 提示 模式：为了确保一个回调是异步执行的，我们可以使用`process.nextTick()`。

## Node.js 回调函数的设计规则
在Node.js中，连续传递风格的API和回调函数遵从某些特定的规则。这些规则应用于Node.js核心API，但实际上也被用户定义模块和应用遵守。所以我们非常有必要理解这些规则并确保设计异步API的时候都遵守它们。
### 最后是回调
在Node.js中，如果一个函数接收一个回调函数作为参数输入，就把这个参数最后一个传入。以下面的Node.js核心API为例：

```
fs.readFile(filename,[options],callback);
```
从前面这个函数的签名可以看到，回调函数是放在最后一位，即便前面是一个可选参数。这样做的目的是函数的调用更加可读。
### 先是错误
在CPS模式中，错误作为另外一种结果传递，就意味着使用了回调。在Node.js中，CPS模式的函数产生的错误经常作为第一个参数传到回调函数中。如果操作成功，没有错误，第一个参数采用null或者undefined。下面的代码展示了如何定义一个符合规则的回调函数：

```
fs.readFile('foo.txt', 'utf8', function(err, data) {
  if(err)
    handleError(err);
  else
    processData(data);
});
```
一直检查是否存在错误是一个非常好的实践，如果不这样做，debug将会变得困难并且很难发现可能失败的代码。另外一个需要考虑的原则是错误应该是`Error`类型。这意味着简单的字符串或数字不能作为错误对象传入。
### 传递错误
同步函数一般使用`throw`命令传递错误，以使错误在被捕获前跳过调用栈。然而在在异步的CPS中，宜简单地将错误传递到CPS链下一个回调中。典型的模式如下：

```
var fs = require('fs');
function readJSON(filename, callback) {
  fs.readFile(filename, 'utf8', function(err, data) {
    var parsed;
    if(err)
      //propagate the error and exit the current function
      return callback(err);

    try {
      //parse the file contents
      parsed = JSON.parse(data);
    } catch(err) {
      //catch parsing errors
      return callback(err);
    }
    //no errors, propagate just the data
    callback(null, parsed);
  });
};
```
我们从上面的例子中可以看到回调如何传递正确的结果或传递错误。
### 未捕获的异常
你可能已经在前面定义的`readJSON()`函数中看到，为了避免在`fs.readFile()`中抛出异常，我们用一个`try catch`代码块把JSON.parse()包起来。在一个异步的回调内部抛出异常，这样我们使异常跳到事件循环，使其不会被传递到下一个回调。
在Node.js中，这是一个无法恢复的状态，程序会停止并在`stderr`接口上打印错误。为了重现这个问题，我们把`readJSON()`函数中的`try-catch`模块移除：

```
var fs = require('fs');
function readJSONThrows(filename, callback) {
  fs.readFile(filename, 'utf8', function(err, data) {
    if(err)
      return callback(err);
    //没有错误，直接传递数据
    callback(null, JSON.parse(data));
  });
};
```
在刚定义的函数中，没法捕获`JSON.parse()`抛出的错误。我们试一下，用下面的代码来解析一个不合法的JSON文件：

```
readJSONThrows('nonJSON.txt', function(err) {
  console.log(err);
});
```
这将导致程序突然停止，下面的异常将会被打印到控制台上：

```
SyntaxError: Unexpected token d
at Object.parse (native)
    at [...]/06_uncaught_exceptions/uncaught.js:7:25
    at fs.js:266:14
    at Object.oncomplete (fs.js:107:15)

```
根据栈追踪信息，可以得出问题从`fs.js`模块开始，差不多是在这个点，原生API完成了读操作，并通过事件循环将结果返回给`fs.readFile()`函数。显而易见，异常从回调函数到了我们看到的栈然后直接到了事件循环，在这里被捕获并抛出到了控制台。
这也意味着用`try-catch`包装`readJSONThrows()`也不会起作用，因为块作用的栈和回调被触发的栈不同。下面的代码展示了我们刚刚描述的反模式：

```
try {
  readJSONThrows('nonJSON.txt', function(err, result) {
    [...]
  });
} catch(err) {
  console.log('This will not catch the JSON parsing exception');
}
```
前面代码中的`catch`声明将永远不会接收到JSON解析的异常，因为它会返回到显示异常的栈，我们刚看到这个栈在事件循环中结束，并没有传递到触发异步操作的函数。
我们刚说到，当异常到达事件循环时，程序就终止了；但是，在完全终止前，仍然有机会来运行一些清理、打印处日志。当异常发生时，Node.js在结束进程钱，会发出一个特别的事件，叫做`uncaughtException`。下面的代码展示了一个示例：

```
process.on('uncaughtException', function(err){
  console.error('这将被最终捕获 ' +
    'JSON解析异常: ' + err.message);
  //没有这一句，程序将会继续。
  process.exit(1);
});
```
一个未捕获的异常会使应用程序无法保证其一致性，从而导致不可预见的问题，理解这一点非常重要。例如，可能仍然会有未完成的I/O请求在运行或者闭包会变得不一致，这也是建议在生产环境中发生未知异常时直接退出程序的原因。


